### ISSUE TITLE
[MSK - Option 4] Update option 4 to support IAM-authenticated clusters

### ISSUE THREAD

**Issue by dscpinheiro** [aws-solutions/streaming-data-solution-for-amazon-kinesis-and-amazon-msk#43]
In the current version of the solution (`v1.6.0`), the Amazon Kinesis Analytics Studio resource includes the required connector for IAM auth (`aws-msk-iam-auth`). However, even after updating the SQL statements to use the correct properties, they will fail as the notebook doesn't have the required IAM permissions.

**Required changes**
- Update the [README file](https://github.com/aws-solutions/aws-streaming-data-solution-for-amazon-kinesis-and-amazon-msk/blob/main/source/docs/README-MSK.md#4th-pattern) to mention the properties required for IAM:
```diff
-'properties.security.protocol' = 'SSL',
-'properties.ssl.truststore.location' = '/usr/lib/jvm/java-11-amazon-corretto/lib/security/cacerts',
-'properties.ssl.truststore.password' = 'changeit'

+'properties.security.protocol' = 'SASL_SSL',
+'properties.sasl.mechanism' = 'AWS_MSK_IAM',
+'properties.sasl.jaas.config' = 'software.amazon.msk.auth.iam.IAMLoginModule required;',
+'properties.sasl.client.callback.handler.class' = 'software.amazon.msk.auth.iam.IAMClientCallbackHandler'
```

- Update the [Studio notebook role](https://github.com/aws-solutions/aws-streaming-data-solution-for-amazon-kinesis-and-amazon-msk/blob/main/source/lib/kda-flink-studio.ts#L30) to include the IAM permissions for Amazon MSK (similar to what's done for Lambda):
https://github.com/aws-solutions/aws-streaming-data-solution-for-amazon-kinesis-and-amazon-msk/blob/f41510d62f96d42d98201befd9f0f915b7d74b14/source/lib/msk-consumer.ts#L135-L151

**Comment by tabdunabi** [comment]
The enhancement did not receive enough support to be added to the roadmap.
