### ISSUE TITLE
[MSK - Option 1] Provide custom configuration

### ISSUE THREAD

**Issue by dscpinheiro** [aws-solutions/streaming-data-solution-for-amazon-kinesis-and-amazon-msk#44]
When the solution launches an Amazon MSK cluster, the [default configuration](https://docs.aws.amazon.com/msk/latest/developerguide/msk-default-configuration.html) is always used.

It'd be nice to have a parameter where a custom configuration (ARN and revision) could be provided.

**Comment by tabdunabi** [comment]
The enhancement did not receive enough support to be added to the roadmap.
