### ISSUE TITLE
[MSK - Option 1] Update client to use latest "aws-msk-iam-auth" version

### ISSUE THREAD

**Issue by dscpinheiro** [aws-solutions/streaming-data-solution-for-amazon-kinesis-and-amazon-msk#46]
A new version of `aws-msk-iam-auth` has been released in September (https://github.com/aws/aws-msk-iam-auth/releases/tag/v1.1.1).

**Comment by tabdunabi** [comment]
The enhancement did not receive enough support to be added to the roadmap.
